-- Add CMS settings for Datenschutz page sections 2-12
INSERT INTO public.site_settings (key, value, type, category, label, description) VALUES
('legal_privacy_section2_title', 'Verantwortliche Stelle', 'text', 'legal', 'Datenschutz Sektion 2 Titel', 'Titel für Verantwortliche Stelle'),
('legal_privacy_section2_content', 'Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist der Betreiber dieser Plattform. Die verantwortliche Stelle entscheidet allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten.', 'textarea', 'legal', 'Datenschutz Sektion 2 Inhalt', 'Inhalt für Verantwortliche Stelle'),
('legal_privacy_section3_title', 'Erhebung und Speicherung personenbezogener Daten', 'text', 'legal', 'Datenschutz Sektion 3 Titel', 'Titel für Datenerhebung'),
('legal_privacy_section3_content', 'Bei der Nutzung unserer Plattform erheben wir verschiedene personenbezogene Daten. Personenbezogene Daten sind Daten, mit denen Sie persönlich identifiziert werden können.', 'textarea', 'legal', 'Datenschutz Sektion 3 Inhalt', 'Inhalt für Datenerhebung'),
('legal_privacy_section4_title', 'Registrierungsdaten', 'text', 'legal', 'Datenschutz Sektion 4 Titel', 'Titel für Registrierungsdaten'),
('legal_privacy_section4_content', 'Bei der Registrierung auf unserer Plattform werden folgende Daten erhoben: E-Mail-Adresse, Passwort (verschlüsselt gespeichert), Zeitpunkt der Registrierung. Diese Daten sind für die Nutzung unserer Dienste erforderlich.', 'textarea', 'legal', 'Datenschutz Sektion 4 Inhalt', 'Inhalt für Registrierungsdaten'),
('legal_privacy_section5_title', 'Profildaten', 'text', 'legal', 'Datenschutz Sektion 5 Titel', 'Titel für Profildaten'),
('legal_privacy_section5_content', 'Wenn Sie ein Profil erstellen, können Sie freiwillig weitere Daten angeben: Anzeigename, Alter, Standort (Kanton, Stadt), Beschreibung, Fotos, Kontaktdaten (Telefon, E-Mail, Website, Social Media). Diese Daten werden öffentlich auf der Plattform angezeigt.', 'textarea', 'legal', 'Datenschutz Sektion 5 Inhalt', 'Inhalt für Profildaten'),
('legal_privacy_section6_title', 'Nutzungsdaten', 'text', 'legal', 'Datenschutz Sektion 6 Titel', 'Titel für Nutzungsdaten'),
('legal_privacy_section6_content', 'Bei der Nutzung unserer Plattform werden automatisch technische Daten erfasst: IP-Adresse (anonymisiert), Browser-Typ und -Version, Betriebssystem, Referrer URL, Zeitpunkt des Zugriffs. Diese Daten dienen der Sicherheit und Optimierung unserer Dienste.', 'textarea', 'legal', 'Datenschutz Sektion 6 Inhalt', 'Inhalt für Nutzungsdaten'),
('legal_privacy_section7_title', 'Cookies', 'text', 'legal', 'Datenschutz Sektion 7 Titel', 'Titel für Cookies'),
('legal_privacy_section7_content', 'Unsere Website verwendet Cookies. Cookies sind kleine Textdateien, die auf Ihrem Endgerät gespeichert werden. Wir verwenden nur technisch notwendige Cookies für die Authentifizierung und Session-Verwaltung. Sie können Cookies in Ihren Browser-Einstellungen deaktivieren.', 'textarea', 'legal', 'Datenschutz Sektion 7 Inhalt', 'Inhalt für Cookies'),
('legal_privacy_section8_title', 'Weitergabe von Daten', 'text', 'legal', 'Datenschutz Sektion 8 Titel', 'Titel für Datenweitergabe'),
('legal_privacy_section8_content', 'Eine Weitergabe Ihrer personenbezogenen Daten an Dritte erfolgt nur, wenn dies zur Vertragserfüllung erforderlich ist, Sie ausdrücklich eingewilligt haben, oder eine gesetzliche Verpflichtung besteht. Ihre Profildaten sind öffentlich einsehbar, sofern Sie ein Profil erstellen.', 'textarea', 'legal', 'Datenschutz Sektion 8 Inhalt', 'Inhalt für Datenweitergabe'),
('legal_privacy_section9_title', 'Ihre Rechte', 'text', 'legal', 'Datenschutz Sektion 9 Titel', 'Titel für Benutzerrechte'),
('legal_privacy_section9_content', 'Sie haben folgende Rechte bezüglich Ihrer Daten: Auskunft über gespeicherte Daten, Berichtigung unrichtiger Daten, Löschung Ihrer Daten, Einschränkung der Verarbeitung, Datenübertragbarkeit, Widerspruch gegen die Verarbeitung. Kontaktieren Sie uns für die Ausübung dieser Rechte.', 'textarea', 'legal', 'Datenschutz Sektion 9 Inhalt', 'Inhalt für Benutzerrechte'),
('legal_privacy_section10_title', 'Datensicherheit', 'text', 'legal', 'Datenschutz Sektion 10 Titel', 'Titel für Datensicherheit'),
('legal_privacy_section10_content', 'Wir setzen technische und organisatorische Sicherheitsmassnahmen ein: SSL/TLS-Verschlüsselung, sichere Passwort-Speicherung (bcrypt), Zugangskontrolle, regelmässige Sicherheitsupdates. Trotz aller Massnahmen kann keine absolute Sicherheit garantiert werden.', 'textarea', 'legal', 'Datenschutz Sektion 10 Inhalt', 'Inhalt für Datensicherheit'),
('legal_privacy_section11_title', 'Speicherdauer', 'text', 'legal', 'Datenschutz Sektion 11 Titel', 'Titel für Speicherdauer'),
('legal_privacy_section11_content', 'Ihre Daten werden so lange gespeichert, wie Ihr Konto aktiv ist. Bei Kontolöschung werden alle personenbezogenen Daten innerhalb von 30 Tagen gelöscht, sofern keine gesetzlichen Aufbewahrungspflichten bestehen.', 'textarea', 'legal', 'Datenschutz Sektion 11 Inhalt', 'Inhalt für Speicherdauer'),
('legal_privacy_section12_title', 'Änderungen dieser Datenschutzerklärung', 'text', 'legal', 'Datenschutz Sektion 12 Titel', 'Titel für Änderungen'),
('legal_privacy_section12_content', 'Wir behalten uns vor, diese Datenschutzerklärung anzupassen, um sie an geänderte Rechtslagen oder Änderungen unserer Dienste anzupassen. Die aktuelle Version ist stets auf unserer Website verfügbar.', 'textarea', 'legal', 'Datenschutz Sektion 12 Inhalt', 'Inhalt für Änderungen'),
('toast_profile_saved', 'Profil erfolgreich gespeichert', 'text', 'messages', 'Toast: Profil gespeichert', 'Erfolgsmeldung beim Speichern'),
('toast_profile_error', 'Fehler beim Speichern des Profils', 'text', 'messages', 'Toast: Profil Fehler', 'Fehlermeldung beim Speichern'),
('toast_login_success', 'Erfolgreich angemeldet', 'text', 'messages', 'Toast: Login Erfolg', 'Erfolgsmeldung bei Anmeldung'),
('toast_login_error', 'Anmeldung fehlgeschlagen', 'text', 'messages', 'Toast: Login Fehler', 'Fehlermeldung bei Anmeldung'),
('toast_logout_success', 'Erfolgreich abgemeldet', 'text', 'messages', 'Toast: Logout Erfolg', 'Erfolgsmeldung bei Abmeldung'),
('toast_register_success', 'Konto erfolgreich erstellt', 'text', 'messages', 'Toast: Registrierung Erfolg', 'Erfolgsmeldung bei Registrierung'),
('toast_register_error', 'Registrierung fehlgeschlagen', 'text', 'messages', 'Toast: Registrierung Fehler', 'Fehlermeldung bei Registrierung'),
('toast_photo_uploaded', 'Foto erfolgreich hochgeladen', 'text', 'messages', 'Toast: Foto hochgeladen', 'Erfolgsmeldung bei Foto-Upload'),
('toast_photo_error', 'Fehler beim Hochladen des Fotos', 'text', 'messages', 'Toast: Foto Fehler', 'Fehlermeldung bei Foto-Upload'),
('toast_photo_deleted', 'Foto erfolgreich gelöscht', 'text', 'messages', 'Toast: Foto gelöscht', 'Erfolgsmeldung bei Foto-Löschung'),
('toast_favorite_added', 'Zu Favoriten hinzugefügt', 'text', 'messages', 'Toast: Favorit hinzugefügt', 'Erfolgsmeldung bei Favorit'),
('toast_favorite_removed', 'Aus Favoriten entfernt', 'text', 'messages', 'Toast: Favorit entfernt', 'Erfolgsmeldung bei Favorit-Entfernung'),
('toast_message_sent', 'Nachricht erfolgreich gesendet', 'text', 'messages', 'Toast: Nachricht gesendet', 'Erfolgsmeldung bei Kontakt'),
('toast_message_error', 'Fehler beim Senden der Nachricht', 'text', 'messages', 'Toast: Nachricht Fehler', 'Fehlermeldung bei Kontakt'),
('toast_password_reset_sent', 'Passwort-Reset E-Mail wurde gesendet', 'text', 'messages', 'Toast: Passwort Reset', 'Erfolgsmeldung bei Passwort-Reset'),
('toast_password_changed', 'Passwort erfolgreich geändert', 'text', 'messages', 'Toast: Passwort geändert', 'Erfolgsmeldung bei Passwort-Änderung'),
('toast_verification_submitted', 'Verifizierung eingereicht', 'text', 'messages', 'Toast: Verifizierung eingereicht', 'Erfolgsmeldung bei Verifizierung'),
('toast_report_submitted', 'Meldung erfolgreich eingereicht', 'text', 'messages', 'Toast: Meldung eingereicht', 'Erfolgsmeldung bei Meldung'),
('toast_setting_saved', 'Einstellung erfolgreich gespeichert', 'text', 'messages', 'Toast: Einstellung gespeichert', 'Erfolgsmeldung bei Einstellungen'),
('toast_generic_error', 'Ein Fehler ist aufgetreten', 'text', 'messages', 'Toast: Allgemeiner Fehler', 'Allgemeine Fehlermeldung')
ON CONFLICT (key) DO NOTHING;