-- Add new site_settings for complete CMS independence (only non-existing keys)
INSERT INTO site_settings (key, label, description, value, type, category) VALUES
-- Navigation (new keys only)
('nav_prices', 'Navigation: Preise Link', 'Text für Preise & Pakete Link in Navigation', 'Preise & Pakete', 'text', 'navigation'),
('nav_create_ad', 'Navigation: Inserat Link', 'Text für Inserat aufgeben Link', 'Inserat aufgeben', 'text', 'navigation'),
('nav_agb', 'Navigation: AGB Link', 'Text für AGB Link', 'AGB', 'text', 'navigation'),
('nav_privacy', 'Navigation: Datenschutz Link', 'Text für Datenschutzerklärung Link', 'Datenschutzerklärung', 'text', 'navigation'),
('nav_admin', 'Navigation: Admin Link', 'Text für Admin Link', 'Admin', 'text', 'navigation'),
('nav_admin_dashboard', 'Navigation: Dashboard Link', 'Text für Admin Dashboard Link', 'Admin Dashboard', 'text', 'navigation'),
('nav_welcome_title', 'Navigation: Willkommenstitel', 'Titel in der Navigation/Auth', 'Willkommen bei ESCORIA', 'text', 'navigation'),

-- Footer (new keys only)
('footer_section_cantons', 'Footer: Kantone Titel', 'Titel für Kantone-Sektion', 'Beliebte Kantone', 'text', 'content'),
('footer_section_info', 'Footer: Info Titel', 'Titel für Informationen-Sektion', 'Informationen', 'text', 'content'),
('footer_section_legal', 'Footer: Rechtliches Titel', 'Titel für Rechtliches-Sektion', 'Rechtliches', 'text', 'content'),
('footer_section_cta', 'Footer: CTA Titel', 'Titel für Call-to-Action Sektion', 'Inserat erstellen', 'text', 'content'),
('footer_cta_description', 'Footer: CTA Beschreibung', 'Beschreibung für Call-to-Action', 'Erstelle jetzt dein kostenloses Inserat und erreiche tausende potenzielle Interessenten in der ganzen Schweiz.', 'textarea', 'content'),
('footer_link_prices', 'Footer: Preise Link Text', 'Text für Preise & Pakete Link', 'Preise & Pakete', 'text', 'content'),
('footer_link_advertising', 'Footer: Werbung Link Text', 'Text für Werbung schalten Link', 'Werbung schalten', 'text', 'content'),

-- Banner page settings (completely new category)
('banner_page_title', 'Banner: Seitentitel', 'Haupttitel der Bannerpreise-Seite', 'Werbebanner schalten', 'text', 'content'),
('banner_page_subtitle', 'Banner: Untertitel', 'Untertitel der Bannerpreise-Seite', 'Erreichen Sie tausende potenzielle Kunden mit unseren exklusiven Werbebannern', 'textarea', 'content'),
('banner_popup_name', 'Banner: Popup Name', 'Name des Popup-Banners', 'Popup-Banner', 'text', 'content'),
('banner_popup_description', 'Banner: Popup Beschreibung', 'Beschreibung des Popup-Banners', 'Maximale Aufmerksamkeit beim Seitenaufruf', 'text', 'content'),
('banner_popup_price_day', 'Banner: Popup Preis Tag', 'Popup-Banner Preis pro Tag', 'CHF 80', 'text', 'content'),
('banner_popup_price_week', 'Banner: Popup Preis Woche', 'Popup-Banner Preis pro Woche', 'CHF 504', 'text', 'content'),
('banner_popup_price_month', 'Banner: Popup Preis Monat', 'Popup-Banner Preis pro Monat', 'CHF 2''040', 'text', 'content'),
('banner_popup_features', 'Banner: Popup Features', 'Popup-Banner Features als JSON', '["Erscheint beim Seitenaufruf", "Volle Aufmerksamkeit", "Anpassbare Anzeigerate", "Exklusive Platzierung"]', 'textarea', 'content'),
('banner_top_name', 'Banner: Top Name', 'Name des Top-Banners', 'Top-Banner', 'text', 'content'),
('banner_top_description', 'Banner: Top Beschreibung', 'Beschreibung des Top-Banners', 'Prominent im Kopfbereich jeder Seite', 'text', 'content'),
('banner_top_price_day', 'Banner: Top Preis Tag', 'Top-Banner Preis pro Tag', 'CHF 50', 'text', 'content'),
('banner_top_price_week', 'Banner: Top Preis Woche', 'Top-Banner Preis pro Woche', 'CHF 315', 'text', 'content'),
('banner_top_price_month', 'Banner: Top Preis Monat', 'Top-Banner Preis pro Monat', 'CHF 1''275', 'text', 'content'),
('banner_top_features', 'Banner: Top Features', 'Top-Banner Features als JSON', '["Immer sichtbar", "Hohe Reichweite", "Desktop & Mobile", "Exklusive Platzierung"]', 'textarea', 'content'),
('banner_grid_name', 'Banner: Grid Name', 'Name des Grid-Banners', 'Grid-Banner', 'text', 'content'),
('banner_grid_description', 'Banner: Grid Beschreibung', 'Beschreibung des Grid-Banners', 'Integriert zwischen den Suchergebnissen', 'text', 'content'),
('banner_grid_price_day', 'Banner: Grid Preis Tag', 'Grid-Banner Preis pro Tag', 'CHF 30', 'text', 'content'),
('banner_grid_price_week', 'Banner: Grid Preis Woche', 'Grid-Banner Preis pro Woche', 'CHF 189', 'text', 'content'),
('banner_grid_price_month', 'Banner: Grid Preis Monat', 'Grid-Banner Preis pro Monat', 'CHF 765', 'text', 'content'),
('banner_grid_features', 'Banner: Grid Features', 'Grid-Banner Features als JSON', '["Natürliche Integration", "Kontextbezogen", "Hohe Klickrate", "Exklusive Platzierung"]', 'textarea', 'content'),
('banner_info_results_title', 'Banner: Info Messbar Titel', 'Titel für messbare Ergebnisse Info', 'Messbare Ergebnisse', 'text', 'content'),
('banner_info_results_text', 'Banner: Info Messbar Text', 'Text für messbare Ergebnisse', 'Detaillierte Statistiken zu Impressions und Klicks', 'text', 'content'),
('banner_info_activation_title', 'Banner: Info Aktivierung Titel', 'Titel für schnelle Aktivierung Info', 'Schnelle Aktivierung', 'text', 'content'),
('banner_info_activation_text', 'Banner: Info Aktivierung Text', 'Text für schnelle Aktivierung', 'Ihr Banner ist innerhalb von 24 Stunden live', 'text', 'content'),
('banner_cta_title', 'Banner: CTA Titel', 'Titel für CTA-Sektion', 'Haben Sie Fragen?', 'text', 'content'),
('banner_cta_text', 'Banner: CTA Text', 'Text für CTA-Sektion', 'Kontaktieren Sie uns für eine individuelle Beratung und maßgeschneiderte Angebote.', 'textarea', 'content'),
('banner_cta_button', 'Banner: CTA Button', 'Button-Text für CTA', 'Jetzt Kontakt aufnehmen', 'text', 'content'),

-- Hero section settings (new keys only, hero_subtitle already exists)
('hero_search_title', 'Hero: Suche Titel', 'Titel für Suchbereich', 'Suche', 'text', 'content'),
('hero_reset_button', 'Hero: Reset Button', 'Text für Zurücksetzen-Button', 'Zurücksetzen', 'text', 'content'),
('hero_filters_active', 'Hero: Filter Aktiv', 'Text wenn Filter aktiv sind', 'Filter aktiv', 'text', 'content'),
('hero_gps_button', 'Hero: GPS Button', 'Text für GPS-Suche Button', 'In meiner Nähe suchen', 'text', 'content'),
('hero_gps_detecting', 'Hero: GPS Erkenne', 'Text beim GPS-Erkennen', 'Erkenne Standort...', 'text', 'content'),
('hero_radius_label', 'Hero: Umkreis Label', 'Label für Umkreis-Slider', 'Umkreis', 'text', 'content'),
('hero_back_to_location', 'Hero: Zurück zu Ort', 'Text für Zurück-Button', 'Zurück zur Ortsauswahl', 'text', 'content'),
('hero_canton_placeholder', 'Hero: Kanton Placeholder', 'Placeholder für Kanton-Auswahl', 'Kanton wählen', 'text', 'content'),
('hero_category_placeholder', 'Hero: Kategorie Placeholder', 'Placeholder für Kategorie-Auswahl', 'Alle Kategorien', 'text', 'content'),

-- Dashboard settings (new keys only)
('dashboard_favorites_button', 'Dashboard: Favoriten Button', 'Text für Favoriten-Button', 'Favoriten', 'text', 'content'),
('dashboard_status_pending', 'Dashboard: Status Ausstehend', 'Text für Status "pending"', 'Ausstehend', 'text', 'content'),
('dashboard_status_active', 'Dashboard: Status Aktiv', 'Text für Status "active"', 'Aktiv', 'text', 'content'),
('dashboard_status_rejected', 'Dashboard: Status Abgelehnt', 'Text für Status "rejected"', 'Abgelehnt', 'text', 'content'),
('dashboard_no_profile_title', 'Dashboard: Kein Profil Titel', 'Titel wenn kein Profil vorhanden', 'Noch kein Profil erstellt', 'text', 'content'),
('dashboard_no_profile_text', 'Dashboard: Kein Profil Text', 'Text wenn kein Profil vorhanden', 'Erstelle jetzt dein erstes Inserat und erreiche tausende potenzielle Interessenten.', 'textarea', 'content'),
('dashboard_no_profile_button', 'Dashboard: Kein Profil Button', 'Button-Text wenn kein Profil', 'Jetzt Profil erstellen', 'text', 'content'),
('dashboard_package_title', 'Dashboard: Paket Titel', 'Titel für Inserat-Paket Sektion', 'Dein Inserat-Paket', 'text', 'content'),
('dashboard_package_basic_desc', 'Dashboard: Basic Paket Beschreibung', 'Beschreibung Basic-Paket', 'Basis-Inserat mit Standardsichtbarkeit', 'text', 'content'),
('dashboard_package_premium_desc', 'Dashboard: Premium Paket Beschreibung', 'Beschreibung Premium-Paket', 'Premium-Inserat mit erhöhter Sichtbarkeit', 'text', 'content'),
('dashboard_package_top_desc', 'Dashboard: TOP Paket Beschreibung', 'Beschreibung TOP-Paket', 'TOP-Inserat mit maximaler Sichtbarkeit', 'text', 'content'),
('dashboard_valid_until', 'Dashboard: Gültig bis', 'Label für Gültigkeitsdatum', 'Gültig bis', 'text', 'content'),
('dashboard_upgrade_button', 'Dashboard: Upgrade Button', 'Text für Upgrade-Button', 'Upgrade auf', 'text', 'content'),
('dashboard_extend_button', 'Dashboard: Verlängern Button', 'Text für Verlängern-Button', 'Inserat verlängern', 'text', 'content'),
('dashboard_profile_data_title', 'Dashboard: Profildaten Titel', 'Titel für Profildaten-Sektion', 'Deine Profildaten', 'text', 'content'),
('dashboard_label_name', 'Dashboard: Label Name', 'Label für Name', 'Name', 'text', 'content'),
('dashboard_label_age', 'Dashboard: Label Alter', 'Label für Alter', 'Alter', 'text', 'content'),
('dashboard_label_gender', 'Dashboard: Label Geschlecht', 'Label für Geschlecht', 'Geschlecht', 'text', 'content'),
('dashboard_label_location', 'Dashboard: Label Standort', 'Label für Standort', 'Standort', 'text', 'content'),
('dashboard_label_languages', 'Dashboard: Label Sprachen', 'Label für Sprachen', 'Sprachen', 'text', 'content'),
('dashboard_label_about', 'Dashboard: Label Über mich', 'Label für Über mich', 'Über mich', 'text', 'content'),
('dashboard_label_categories', 'Dashboard: Label Kategorien', 'Label für Kategorien', 'Kategorien', 'text', 'content'),
('dashboard_photos_title', 'Dashboard: Fotos Titel', 'Titel für Fotos-Sektion', 'Deine Fotos', 'text', 'content'),
('dashboard_privacy_title', 'Dashboard: Datenschutz Titel', 'Titel für Datenschutz-Sektion', 'Datenschutz & Sicherheit', 'text', 'content'),
('dashboard_export_title', 'Dashboard: Export Titel', 'Titel für Datenexport', 'Daten exportieren', 'text', 'content'),
('dashboard_export_text', 'Dashboard: Export Text', 'Text für Datenexport', 'Lade alle deine Profildaten als JSON-Datei herunter.', 'text', 'content'),
('dashboard_export_button', 'Dashboard: Export Button', 'Button-Text für Export', 'Daten exportieren', 'text', 'content'),
('dashboard_delete_title', 'Dashboard: Löschen Titel', 'Titel für Account-Löschung', 'Account löschen', 'text', 'content'),
('dashboard_delete_text', 'Dashboard: Löschen Text', 'Text für Account-Löschung', 'Alle deine Daten werden unwiderruflich gelöscht.', 'text', 'content'),
('dashboard_delete_button', 'Dashboard: Löschen Button', 'Button-Text für Löschung', 'Account dauerhaft löschen', 'text', 'content'),

-- Profile creation settings (new keys only)
('profile_tab_data', 'Profil: Tab Daten', 'Tab-Name für Profildaten', 'Profildaten', 'text', 'content'),
('profile_tab_listing', 'Profil: Tab Inserat', 'Tab-Name für Inserat-Typ', 'Inserat-Typ', 'text', 'content'),
('profile_tab_photos', 'Profil: Tab Fotos', 'Tab-Name für Fotos', 'Fotos', 'text', 'content'),
('profile_tab_verification', 'Profil: Tab Verifizierung', 'Tab-Name für Verifizierung', 'Verifizierung', 'text', 'content'),
('profile_photos_save_button', 'Profil: Fotos Speichern Button', 'Button-Text für Fotos speichern', 'Fotos speichern und weiter', 'text', 'content'),

-- Auth settings (new keys only)
('auth_password_hint', 'Auth: Passwort Hinweis', 'Hinweis für Passwort-Anforderungen', 'Mindestens 8 Zeichen, 1 Großbuchstabe, 1 Kleinbuchstabe, 1 Zahl', 'text', 'content'),
('auth_loading_login', 'Auth: Lade Login', 'Text beim Login-Laden', 'Anmelden...', 'text', 'content'),
('auth_loading_signup', 'Auth: Lade Registrierung', 'Text beim Registrieren-Laden', 'Registrieren...', 'text', 'content');